# -*- coding: utf-8 -*-
"""GenEd_Class_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJo9fM8Y6HoH6qIg4VeWbag0Zl_fT94q

**Topics Session 2**

- Type casting
- Type conversion
- formatic String
- input funcation

**Task: Age in Days Calculator**

Ask the user to enter their name.

Ask the user to enter their age (in years).

Convert the entered age into days (assuming 1 year = 365 days).

Display a message formatted with their name and age in days.
"""

# user input for age and name
name = input("Enter your name: ")
age = int(input("Enter your age: "))
converter = f"Your age is {age * 365} days"
print(f"Hello {name}! {converter}")

# using format() funcation
name = input("Enter your name: ")
age = int(input("Enter your age: "))
converter = f"Your age is {age * 365} days"
print("Hello {}! {}".format(name, converter))

# using format() funcation and give implicit vaiable position
name = input("Enter your name: ")
age = int(input("Enter your age: "))
converter = f"Your age is {age * 365} days"
print("Hello {0}! {1}".format(name, converter))

# using format() funcation and give implicit vaiable position
name = input("Enter your name: ")
age = int(input("Enter your age: "))
converter = "Your age is " + int(age * 365) + " days"
print("Hello {0}! {1}".format(name, converter))

# using format() funcation and give implicit vaiable position
name = input("Enter your name: ")
age = int(input("Enter your age: "))
converter = "Your age is " + str(age * 365) + " days"

print("Hello {0}! {1}".format(name, converter))

